SHOP/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    path('', include('shop_app.urls', namespace='shop_app')),
    path('user/', include('users_app.urls', namespace='users_app')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/api/urls.py
from rest_framework import routers
from django.conf.urls import include
from django.urls import path

from . import views

router = routers.DefaultRouter()
router.register('department', views.DepartmentViewSet)
router.register('item', views.ItemViewSet)
router.register('shop', views.ShopViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

shop_app/urls.py
from django.urls import path, include
from .views import (IndexView,
                    ItemListView,
                    ItemCreate,
                    ItemDetail,
                    ItemUpdate,
                    ItemDelete,
                    ShopListView,
                    ShopCreate,
                    ShopDetail,
                    ShopUpdate,
                    ShopDelete)

app_name = 'shop_app'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('item_list/', ItemListView.as_view(), name='item_list'),
    path('item_create/', ItemCreate.as_view(), name='item_create'),
    path('item_detail/<int:pk>/', ItemDetail.as_view(), name='item_detail'),
    path('item_update/<int:pk>/', ItemUpdate.as_view(), name='item_update'),
    path('item_delete/<int:pk>/', ItemDelete.as_view(), name='item_delete'),
    path('api/', include('shop_app.api.urls')),
    path('shop_list/', ShopListView.as_view(), name='shop_list'),
    path('shop_create/', ShopCreate.as_view(), name='shop_create'),
    path('shop_detail/<int:pk>/', ShopDetail.as_view(), name='shop_detail'),
    path('shop_update/<int:pk>/', ShopUpdate.as_view(), name='shop_update'),
    path('shop_delete/<int:pk>/', ShopDelete.as_view(), name='shop_delete'),
]

users_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView



app_name = 'users_app'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users_app/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('users_app:login')), name='logout'),
]

shop_app/models.py
from django.db import models
from PIL import Image

# Create your models here.
from django.urls import reverse


class Shop(models.Model):
    name = models.CharField(
        max_length=128,
        verbose_name='Наименование магазина'
    )
    address = models.CharField(
        max_length=256,
        verbose_name='Адрес магазина'
    )
    staff_amount = models.IntegerField(
        blank=True,
        null=True
    )

    image = models.ImageField(
        upload_to='image/shop_app/%Y/%m/%d',
        default=None,
        blank=True,
        null=True,
        verbose_name='Изображения'
    )

    def save(self, *args, **kwargs):
        try:
            this_entry = Shop.objects.get(id=self.id)
            if this_entry.image != self.image:
                this_entry.image.delete(save=False)
        except:
            pass
        super(Shop, self).save(*args, **kwargs)
        image = Image.open(self.image.path)
        max_size = max(image.size[0], image.size[1])
        multiplier = max_size / 1200
        image = image.resize((round(image.size[0] / multiplier), round(image.size[1] / multiplier)), Image.ANTIALIAS)
        image.save(self.image.path)
        print(image.size)

        image.save(self.image.path)

    def delete(self, *args, **kwargs):
        self.image.delete(save=False)

        super(Shop, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop_app:shop_update', args=(self.id,))

    def __str__(self):
        return f'{self.name} {self.address}'

    class Meta:
        verbose_name = 'Магазин'
        verbose_name_plural = "Магазины"
        ordering = (
            'name',
        )


class Department(models.Model):
    SPHERE = (
        ('1', 'Продукты'),
        ('2', 'Игрушки'),
        ('3', 'Одежда')
    )
    sphere = models.CharField(
        max_length=128,
        choices=SPHERE,
        verbose_name='сфера'
    )
    staff_amount = models.IntegerField()
    shop = models.ForeignKey(
        'Shop',
        on_delete=models.DO_NOTHING,
        verbose_name='Магазин'
    )
    is_delete = models.BooleanField(
        default=False,
        verbose_name='Удалено'
    )

    def delete(self, using=None, keep_parents=False):
        self.is_delete = True
        self.save()

    def save(self, *agrs, **kwargs):
        return super(Department, self).save(*agrs, **kwargs)

    def __str__(self):
        return f'{self.get_sphere_display()} {self.shop}'

    class Meta:
        verbose_name = 'Департамент'
        verbose_name_plural = "Департаменты"


class Item(models.Model):
    name = models.CharField(
        max_length=128,
        verbose_name='Наименование товара'
    )
    description = models.CharField(
        max_length=1024,
        verbose_name='Описание товара'
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Цена'
    )
    department = models.ForeignKey(
        Department,
        on_delete=models.DO_NOTHING,
        verbose_name='Департамент'
    )
    image = models.ImageField(
        upload_to='image/shop_app/%Y/%m/%d',
        default=None,
        blank=True,
        null=True,
        verbose_name='Изображения'
    )

    def save(self, *args, **kwargs):
        try:
            this_entry = Item.objects.get(id=self.id)
            if this_entry.image != self.image:
                this_entry.image.delete(save=False)
        except:
            pass
        super(Item, self).save(*args, **kwargs)
        image = Image.open(self.image.path)
        max_size = max(image.size[0], image.size[1])
        multiplier = max_size / 1200
        image = image.resize((round(image.size[0] / multiplier), round(image.size[1] / multiplier)), Image.ANTIALIAS)
        image.save(self.image.path)
        print(image.size)

        image.save(self.image.path)

    def delete(self, *args, **kwargs):
        self.image.delete(save=False)

        super(Item, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop_app:item_update', args=(self.id,))

    def __str__(self):
        return f'{self.name} {self.price} {self.department}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = "Товары"
        ordering = (
            'name',
            'price',
        )

shop_app/forms.py
from django import forms
from .models import (Item,
                     Shop)


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = '__all__'

shop_app/api/views.py
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from .serializers import (
    DepartmentSerializer,
    ItemSerializer,
    ShopSerializer
)

from ..models import (
    Department,
    Item,
    Shop
)


class DepartmentViewSet(ModelViewSet):
    queryset = Department.objects.filter(is_delete=False)
    # queryset = Department.objects.all()
    serializer_class = DepartmentSerializer

    def list(self, request, *args, **kwargs):
        print('HI i am list method')
        return super(DepartmentViewSet, self).list(request, *args, **kwargs)

    @action(methods=['get'], detail=False)
    def all_instances(self, request, *args, **kwargs):
        queryset = Department.objects.all()
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)



    # def retrieve(self, request, *args, **kwargs):  #  получение отдельной объект
    # def create(self, request, *args, **kwargs):    #  создание сущности объекта
    # def update(self, request, *args, **kwargs):    #  обновление объекта
    # def destroy(self, request, *args, **kwargs):   #  удаление объекта


class ItemViewSet(ModelViewSet):
    queryset = Item.objects.all()
    # queryset = Department.objects.all()
    serializer_class = ItemSerializer


class ShopViewSet(ModelViewSet):
    queryset = Shop.objects.all()
    # queryset = Department.objects.all()
    serializer_class = ShopSerializer

shop_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    View,
    TemplateView,
    DetailView,
)

from .models import (
    Item,
    Shop,
    Department,
)

from .forms import (
    ItemForm, ShopForm,
)


def index(request):
    return render(request, 'shop_app/base.html', context={})


class IndexView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('users_app:login')
    template_name = 'shop_app/base.html'


class ItemListView(ListView):
    template_name = 'shop_app/item_list.html'
    model = Item
    context_object_name = 'item_list'
    paginate_by = 12

    def get_queryset(self):
        # return Item.objects.filter()
        return Item.objects.select_related('department__shop', 'department')

    def get_paginate_by(self, queryset):
        return super(ItemListView, self).get_paginate_by(self.get_queryset())

    def get(self, request, *args, **kwargs):
        return super(ItemListView, self).get(request, *args, **kwargs)


class ItemCreate(CreateView):
    template_name = 'shop_app/item_create.html'
    model = Item
    form_class = ItemForm


class ItemDetail(DetailView):
    model = Item
    template_name = 'shop_app/item_detail.html'
    context_object_name = 'item'

    def get_queryset(self):
        return Item.objects.select_related('department', 'department__shop')


class ItemUpdate(UpdateView):
    template_name = 'shop_app/item_create.html'
    model = Item
    form_class = ItemForm


class ItemDelete(DeleteView):
    model = Item
    # при успешном удалении редиректим на....
    success_url = reverse_lazy('shop_app:item_list')
    # указываем шаблон для страницы подтверждения удаления
    template_name = 'shop_app/confirm_delete.html'


class ShopListView(ListView):
    template_name = 'shop_app/shop_list.html'
    model = Shop
    context_object_name = 'shop_list'
    paginate_by = 3

    def get_queryset(self):
        # return Shop.objects.filter()
        return Shop.objects.all()

    def get_paginate_by(self, queryset):
        return super(ShopListView, self).get_paginate_by(self.get_queryset())

    def get(self, request, *args, **kwargs):
        return super(ShopListView, self).get(request, *args, **kwargs)


class ShopCreate(CreateView):
    template_name = 'shop_app/shop_create.html'
    model = Shop
    form_class = ShopForm


class ShopDetail(DetailView):
    model = Shop
    template_name = 'shop_app/shop_detail.html'
    context_object_name = 'shop'

    def get_queryset(self):
        return Shop.objects.all()


class ShopUpdate(UpdateView):
    template_name = 'shop_app/shop_create.html'
    model = Shop
    form_class = ShopForm


class ShopDelete(DeleteView):
    model = Shop
    # при успешном удалении редиректим на....
    success_url = reverse_lazy('shop_app:shop_list')
    # указываем шаблон для страницы подтверждения удаления
    template_name = 'shop_app/shop_delete.html'

shop_app/templates/shop_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      My django app
    {% endblock%}
  </title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
  <script src="{% static 'shop_app/js/django_form.js' %}"></script>
</head>
<body>
  {% csrf_token %}
  <script>
    let CSRF = document.getElementsByName('csrfmiddlewaretoken')[0].value;
    let URL_PREFIX = 'http' + '://' + '{{ request.META.HTTP_HOST }}' + '/';
    let axios_instance = axios.create(
        {
            baseURL: URL_PREFIX,
            headers:{'X-CSRFToken':CSRF},
        }
    );
  </script>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>

            </ul>
            <ul class="navbar-nav mr-left">
              <li class="nav-item left">
                <a class="nav-link " href="{% url 'users_app:logout' %}"
                   tabindex="-1" aria-disabled="true">Logout</a>
              </li>
            </ul>
          </div>
        </nav>

{#        {% if user.is_authenticated %}#}
{#          <div class="col-lg-6 offset-3">#}
{#            <img src="{% static 'shop_app/image/download.jpeg' %}"#}
{#                 style="max-width: 300px">#}
{#          </div>#}
{#        {% endif %}#}
      </div>
    </div>
    <div class="row">
    {% block body %}
      <!-- some context-->
      <div class="col-lg-12">
        <a href="{% url 'shop_app:item_list' %}">Товары</a>
        <a href="{% url 'shop_app:shop_list' %}">Shops</a>
      </div>
    {% endblock %}
    </div>
  </div>
</body>
</html>

shop_app/templates/shop_app/confirm_delete.html
{% extends 'shop_app/base.html' %}
{% block title %}
  Удаление продукта
{% endblock %}
{% block body %}
  <div class="col-lg-6 offset-3">
    <form id="confirm_delete" method="post" >
      {% csrf_token %}
      Вы действительно хотите удалить "{{ object }}"?
      <input type="submit" value="Ок" />
      <a href="{% url 'shop_app:item_update' object.id %}">Отмена</a>
    </form>
  </div>
{% endblock %}

shop_app/templates/shop_app/item_create.html
{% extends 'shop_app/base.html' %}
{% block title %}
  Создание продукта
{% endblock %}
{% block body %}
  <div class="col-lg-12">
    <form id="item_form" method="post"
          enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <p>
        <button type="submit">
          {% if form.instance.id %}
            Обновить
          {% else %}
            Сохранить
          {% endif %}
        </button>
      </p>
    </form>
    {% if form.instance.id %}
      <a href="{% url 'shop_app:item_delete' form.instance.id %}">
        Удалить
      </a>
    {% endif %}
  <script type="application/javascript">
    bootstrap_form('#item_form')
  </script>
  </div>
{% endblock %}

shop_app/templates/shop_app/item_detail.html
{% extends "shop_app/base.html"%}
{% block title %}
  Детализация по продукту
{% endblock %}

{% block body %}
  <div class="col-lg-4 offset-4">
    <a class="my_class" href="{% url 'shop_app:item_update' item.id %}">
     {{ item }}
    </a>
    {% if item.image %}
      <p>
        <img src="{{ item.image.url }}" style="max-width: 10rem">
      </p>
    {% else %}
      <p >
        Изображение отсутствует
      </p>
    {% endif %}
  </div>
{% endblock %}

shop_app/templates/shop_app/item_list.html
{% extends 'shop_app/base.html' %}
{% load static %}
{% block title %}
  Список товаров
{% endblock %}

{% block body %}
  <div class="col-lg-12 text-center">
    <a href="{% url 'shop_app:index' %}">На главную</a>
  </div>

  {% for item in item_list %}
    <div class="card col-lg-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">
          <a href="{% url 'shop_app:item_detail' item.id %}">
            {{ item.name }}
          </a>
        </h5>
        <p class="card-text">
          <p>
            Магазин {{ item.department.shop.name }}
          </p>
          {% if item.image %}
            <p>
              <img src="{{ item.image.url }}" style="max-width: 10rem">
            </p>
          {% else %}
            <p >
              Изображение отсутствует
            </p>
          {% endif %}

          <p>
            Цена: {{ item.price }}
          </p>
        </p>
      </div>
    </div>
  {% endfor %}
  {% if paginator.num_pages > 1 %}

      <div class="col-lg-12">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            {% if page_obj.number > 1 %}
              <li class="page-item"><a class="page-link" href="{{ request.path }}?page=1">&lt;&lt;</a></li>
            {% endif %}
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                  &lt;
                </a>
              </li>
            {% endif %}

            {% for pn in paginator.page_range %}
              {% if page_obj.number != pn %}

                <li class="page-item">
                  <a class="page-link" href="{{ request.path }}?page={{ pn }}">
                    {{ pn }}
                  </a>
                </li>
                {% else %}
                <li class="page-item page-item active"><a class="page-link" href="#">{{ pn }}</a></li>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">
                  &gt;
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">
                  &gt;&gt;
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>
{% endif %}
  <div class="col-lg-12 mt-2 text-center ">
    <a class="btn btn-info form-control" href="{% url 'shop_app:item_create' %}">
      Создать продукт
    </a>
  </div>
{% endblock %}

shop_app/templates/shop_app/shop_create.html
{% extends 'shop_app/base.html' %}
{% block title %}
  Create a shop
{% endblock %}
{% block body %}
  <div class="col-lg-12">
    <form id="item_form" method="post"
          enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <p>
        <button type="submit">
          {% if form.instance.id %}
            Обновить
          {% else %}
            Сохранить
          {% endif %}
        </button>
      </p>
    </form>
    {% if form.instance.id %}
      <a href="{% url 'shop_app:shop_delete' form.instance.id %}">
        Удалить
      </a>
    {% endif %}
  <script type="application/javascript">
    bootstrap_form('#item_form')
  </script>
  </div>
{% endblock %}

shop_app/templates/shop_app/shop_delete.html
{% extends 'shop_app/base.html' %}
{% block title %}
  Delete a shop
{% endblock %}
{% block body %}
  <div class="col-lg-6 offset-3">
    <form id="confirm_delete" method="post" >
      {% csrf_token %}
      Вы действительно хотите удалить "{{ object }}"?
      <input type="submit" value="Ок" />
      <a href="{% url 'shop_app:shop_update' object.id %}">Отмена</a>
    </form>
  </div>
{% endblock %}

shop_app/templates/shop_app/shop_detail.html
{% extends "shop_app/base.html"%}
{% block title %}
  Детализация по магазину
{% endblock %}

{% block body %}
  <div class="col-lg-4 offset-4">
    <a class="my_class" href="{% url 'shop_app:shop_update' shop.id %}">
     {{ shop }}
    </a>
    {% if shop.image %}
      <p>
        <img src="{{ shop.image.url }}" style="max-width: 10rem">
      </p>
    {% else %}
      <p >
        Изображение отсутствует
      </p>
    {% endif %}
  </div>
{% endblock %}

shop_app/templates/shop_app/shop_list.html
{% extends 'shop_app/base.html' %}
{% load static %}
{% block title %}
  Shop list
{% endblock %}

{% block body %}
  <div class="col-lg-12 text-center">
    <a href="{% url 'shop_app:index' %}">На главную</a>
  </div>

  {% for shop in shop_list %}
    <div class="card col-lg-4" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">
          <a href="{% url 'shop_app:shop_detail' shop.id %}">
            {{ shop.name }}
          </a>
        </h5>
        <p class="card-text">
          <p>
            Address: {{ shop.address }}
          </p>
          {% if shop.image %}
            <p>
              <img src="{{ shop.image.url }}" style="max-width: 10rem">
            </p>
          {% else %}
            <p >
              Изображение отсутствует
            </p>
          {% endif %}

          <p>
            Staff amount: {{ shop.staff_amount }}
          </p>
        </p>
      </div>
    </div>
  {% endfor %}
  {% if paginator.num_pages > 1 %}

      <div class="col-lg-12">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            {% if page_obj.number > 1 %}
              <li class="page-item"><a class="page-link" href="{{ request.path }}?page=1">&lt;&lt;</a></li>
            {% endif %}
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                  &lt;
                </a>
              </li>
            {% endif %}

            {% for pn in paginator.page_range %}
              {% if page_obj.number != pn %}

                <li class="page-item">
                  <a class="page-link" href="{{ request.path }}?page={{ pn }}">
                    {{ pn }}
                  </a>
                </li>
                {% else %}
                <li class="page-item page-item active"><a class="page-link" href="#">{{ pn }}</a></li>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">
                  &gt;
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">
                  &gt;&gt;
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>
{% endif %}
  <div class="col-lg-12 mt-2 text-center ">
    <a class="btn btn-info form-control" href="{% url 'shop_app:shop_create' %}">
      Create a shop
    </a>
  </div>
{% endblock %}